Dockerfile

When the tracer tries to push the metrics to https://trace.agent.datadoghq.com/api/v0.1/collector
we are getting an error as follows:
```
error when requesting to endpoint https://trace.agent.datadoghq.com/api/v0.1/collector: Post https://trace.agent.datadoghq.com/api/v0.1/collector?api_key=[key]: x509: failed to load system roots and no roots provided
```
This PR installs the necessary certificates to handle tls connections.

docker: install ca-certificates

---

agent/receiver.go
config/agent.go

makes it easier to run a minute long profile.

optionally specify an agent timeout

---

quantizer/redis.go
quantizer/redis_test.go

When there are more than one command, the syntax is now:
PIPELINE [ <commands> ]
Where <commands> is a deduplicated and sorted list of commands.
This new format will significantly reduce the cardinality of the
resource set for application which use a lot of pipelined commands.

introduce a new resource syntax for pipelined redis commands

---

agent/agent_test.go
agent/bench_test.go
fixtures/trace.go

Adds a benchmark for the ``agent.Process()``. It doesn't cover the full flow (decoding and encoding) but it's an initial good approach to collect performance from a standalone execution.
* a standalone binary that floods a running agent (it will use ``RandomTrace()`` func)
* an agent build that accepts a ``-profile`` flag so that CPU (or memory) profile is extracted
* a simple command that can start the agent, collect profiles and stop the agent

[benchmark] Trace Process

---

model/services.go
model/services_test.go

In nodes where services are sent from different applications, the ``DeepEqual`` check for services will fail since buffered service and sent services are deeply equal different (in the sense of Go) even if the `metas` are the same.
The check ensures that a partial deep equality will not flush the service list.
It reduces a lot the number of API calls / services encoding in some cases.

[writer] prevent services flush if there is a partial match

---

quantizer/sql.go

Removes the ``defer`` overhead from an hot path, since the ``Process()`` can be called thousand of times per trace.

[profile] replacing a defer with explicit call from an hot path

---

.gitignore
Rakefile
cmd/tracereplay/tracereplay.go

This is the companion of of the `-dumptraces` trace-agent option.

[profile] add a trace-replay binary to feed agent with real data

---

quantizer/sql_test.go

Using an empty log filename is a bit strange, but it does the job.

disable log output when running sql tests

---

quantizer/redis.go
quantizer/redis_test.go

- Resources will contain up to 3 distinct commands. If there are more
commands, the '...' is added to the resource.
- Commands whose name is truncated are ignored.
Before:
BenchmarkTestRedisQuantizer-4  1000000  2010 ns/op  1011 B/op  8 allocs/op
After:
BenchmarkTestRedisQuantizer-4  1000000  2064 ns/op  1012 B/op  8 allocs/op
100% test coverage for quantizer/redis_test.go.

change the redis resource format and handle truncated lines

---

agent/receiver.go
agent/receiver_responses.go
agent/receiver_test.go
fixtures/span.go
fixtures/trace.go
model/client_api.go
model/client_api_test.go

* improves the ``ClientDecoder`` interface to make decoders implementations reusable
* implements the ``jsonDecoder`` and ``msgpackDecoder`` structs to keep references to the internal buffers and decoders; in this way decoders are reusable multiple times
* ``readAll`` re-implementation that overwrites the given buffer without any kind of allocations (the built-in version allocates a new resizable ``Buffer`` and returns a slice descriptor for each request)
* when a decoder is created with the internal ``Buffer``, the buffer has ``minBufferSize`` size. This improves a lot performances because during each request the buffer is resized many times to contain the ``req.Body``
* the request handler hot path, doesn't make useless allocations when a request is handled without errors.
The benchmark …

[optimization] improving pipeline entrypoint performance

---

cmd/tracereplay/tracereplay.go

- Previous version would not handle lines that would exceed default `bufio.Scanner` buffer size.
- Now parses the traces file once for all and stores it in memory.

[tracereplay] fixed tracereplay to handle big data files

---

quantizer/main.go
quantizer/sql.go

Removes the ``Debugf`` call from the ``Quantize`` hot path. In some cases, it takes [2-5]% of profiled execution. We can reintroduce these kind of logs again, when a different logging library is introduced.

[quantizer] remove Debugf from the hot path

---

GLOCKFILE

random commit may 2014 -> v2.6
Especially this commit: https://github.com/cihub/seelog/commit/44c39f31e6c1de8f54d2253da0da5d4a0ed2ab8e
Looked quickly at the CHANGELOG does not seem too bad, see it at https://github.com/cihub/seelog/compare/83d0dcad636b63c066856045962befa246e00c79...v2.6

upgrade seelog logging library

---

agent/agent.go
agent/endpoint.go
agent/trace-agent.ini
agent/writer.go
agent/writer_test.go
config/agent.go

The goal of these commits is to avoid losing payloads when the API is unavailable. A longer description is available in the last commit.

handle errors when sending payloads to endpoints

---

agent/agent.go

3ee25af22bb2597cd505c2ed389664eb1e9949ed introduced a bug by not exiting the main loop after closing the
exit chan. Therefore the program panics when close is called a second
time.
We also use (*Writer).Stop() since it exists.

fix panic when exiting

---

quantizer/redis.go
quantizer/redis_test.go

We remove the '*' mark for duplicate commands in a pipeline.
Before:
BenchmarkTestRedisQuantizer-4  1000000  2228 ns/op  1012 B/op  8 allocs/op
After:
BenchmarkTestRedisQuantizer-4  1000000  2045 ns/op   996 B/op  7 allocs/op

change the redis resource format

---

agent/main.go

- It's possible to receive more than one SIGINT/SIGTERM during the
shutdown process. So we return after closing the exit chan to avoid
panicking when closing it a second time.
- Only request notification for SIGINT/SIGTERM since these are the only
ones we handle.

fix signal handling to avoid closing the exit chan twice

---

.gitignore
Rakefile
gorake.rb

It generates a coverage file for all tests on all packages.

add a :coverage rake task

---

agent/main.go
config/agent.go

This makes the trace-agent an opt-in process, and is important for hosts
that see an unattended upgrade to datadog-agent@5.11.0 (which will be several)
but don't actually intend to submit to the trace-agent

config: exit 0 if Datadog APM is not enabled explicitly

---

agent/main.go
config/config.go
config/config_test.go

- Do not wrap the error when loading fails, so that we can test it.
- Log loading errors unless it's an ENOENT error.
- Log the fact that we are using a configuration file.

log errors when loading configuration files

---

agent/endpoint_test.go
model/payload.go

Using fastest compression saves about 10% CPU cycles but OTOH produces 10% more data. Obviously depends on the data.

[profile] using BestSpeed GZIP compression

---

config/agent.go

It should be usable to override the configuration file, both to enable
and disable the trace agent.

support 'false' for DD_APM_ENABLED

---

model/client_api.go
model/client_api_test.go

Prevent to keep really big buffers if clients are sending too much data. Currently we're dropping buffers bigger than 10MB
* if the clients are sending the same huge payload (so the average is bigger than 10MB), the decoder will be created over and over increasing the CPU usage.

[decoder] big buffers are discarded

---

agent/receiver_responses.go

- Use status code constants.
- Return a 400 error (bad request) instead of a 500 (internal server
error) for decoding errors.

fix http response statuses

---

agent/receiver.go

These changes are in response to a situation where we leaked file descriptors on a high-throughput node,
eventually hitting kernel limits and being unable to accept new traces
It's likely that we were unable to close `request.Body` and release our connection, due to blocking
in the main HTTP loop. To avoid this we:
- set a WriteTimeout on the server, defaulting to 5 seconds, and configurable via `receiver_timeout`
- drop traces on the floor when we can't write them to the outbound `traces` channel

receiver: set a WriteTimeout, and avoid blocking on a full channel

---

Rakefile
agent/main.go
agent/receiver.go

Also remove the -debug flag as we discussed.

do not truncate when logging why a trace could not be normalized

---

agent/concentrator.go
agent/model_test.go
fixtures/stats.go
model/span.go
model/span_test.go
model/stats_test.go
model/statsraw.go
sampler/sampler.go

The root span of a trace can contain a _sample_rate value if the client
sampled spans. When this is the case, we scale stats (hit and error
counts, and durations) by a factor, or weight, equal to `1.0 /
_sample_rate`.
This also means that we have to use floating point values to accumulate
values for `StatsRawBucket`.

weight spans using their sample rate

---

agent/receiver.go
agent/receiver_test.go
model/limited_reader.go
model/limited_reader_test.go

See commit messages for more information.

implement stream decoding

---

Rakefile
agent/sampler.go
sampler/adjust.go
sampler/adjust_test.go
sampler/backend.go
sampler/sampler.go
sampler/sampler_test.go
sampler/score.go
sampler/state.go

Make sampling smarter with some adaptive scoring.
The 2 main internal scoring parameters (offset and slope) were constants, and they weren't suitable for all distributions of traces.
Now, they are frequently adjusted to better fit the input and the maxTPS limit.
- `offset` is now computed based on the ratio between the number of Traces Per Second we keep and the maxTPS set by the config. Every 5s, we increase/decrease the offset (to sample more or less)  accordingly.
- `slope` is now a function of the input distribution (the number of different signatures and the total TPS are parameters). 
The implementation/equation is done is such a way that it has some interesting properties/protections. I won't explain in details why here, but I plan on writing a real algorithmic explanation of it at …

Adaptive sampling — Step 1

---

quantizer/main.go
quantizer/main_test.go
quantizer/sql.go
quantizer/sql_test.go
quantizer/tokenizer.go

some of them can be unbounded and don't materially change the contents
of the query. here's the direct case:
SELECT pg_try_advisory_lock ( ? ) AS tabcdef1235
this could also be quantized to ` SELECT pg_try_advisory_lock ( ? )` but i din't do that.

sql: quantize as aliases.

---

Rakefile
gorake.rb

We need to be able to build the agent without build variables (commit,
branch, etc.) in omnibus.

add an env variable to control the inclusion of build vars in -version

---

config/agent.go
config/config_test.go

The infrastructure agent implements more refined logic for
inferring hostname of the machine this process is running on
https://github.com/DataDog/dd-agent/blob/7cd0986e137683195f129b2a988dd60ca9ccf0ea/utils/hostname.py#L48
Prior to this change, the trace-agent would identify as a different host
than the infra agent in subtle cases (EC2 / GCE for example). This
created phantom hosts and general inconsistency in the UI
We shell out to the infra agent, via the following command, falling back
to running `os.Hostname()` when it fails
```
PYTHONPATH=/opt/datadog-agent/agent /opt/datadog-agent/embedded/bin/python -c "from utils.hostname import get_hostname; print get_hostname()"
```

config: shell out to dd-agent to retrieve hostname

---

Rakefile
agent/agent.go
agent/agent_test.go
agent/info.go
agent/listener.go
agent/receiver_test.go
config/agent.go
glide.lock
glide.yaml
watchdog/info.go
watchdog/info_test.go

Basic funcs returning:
* CPU usage (value between 0 and number of CPU, 0.3 means 30% of one CPU)
* Mem usage (currently allocated bytes from the point of view of the Go memory manager)
* Byte allocation rate (bytes allocated per second)
* Number of TCP Connections

[watchdog] basic funcs returning CPU and Mem usage

---

agent/endpoint.go
agent/writer.go
config/agent.go
config/proxy.go
config/proxy_test.go

when [proxy
settings](https://github.com/DataDog/dd-agent/blob/master/datadog.conf.example#L7-L10) are defined in datadog.conf
update the default client in the writer to submit to a proxy.
fixes #245

config: respect proxy_* settings in agent

---

model/decoder.go
model/decoder_test.go

If a client sends an integer value to the agent, it will be encoded as a
msgpack integer. Reading the binary representation of an integer does
not yield the floating value you expect.

fix the decoding of float64 values from integers

---

agent/agent.go
agent/endpoint.go
agent/main.go
agent/receiver.go
agent/sampler.go
agent/writer.go
sampler/sampler.go
watchdog/logonpanic.go
watchdog/logonpanic_test.go

Follow-up to https://github.com/DataDog/datadog-trace-agent/pull/254 do the same (log and propagate panic) but do it in all goroutines as doing it in main only will only catch a small percentage of possible panics.

[watchdog] ensure agent recovers from and logs its panics in all goroutines

---

agent/endpoint.go
agent/writer.go

Our payload buffering logic passes along a stateful `APIEndpoint`
when it receives upstream errors. A prior PR ( #251  ) added a `client`
to individual APIEndpoints without propagating this value to the error handler
Thus when an endpoint flush failed, all future flushes would use the
zero value for `APIEndpoint.client` which is `nil`

writer: don't discard the client on api errors

---

config/agent.go

let this guy run in the absence of instructions not to. `apm_enabled` and `DD_APM_ENABLED` are still respected for overrides

config: enable agent by default

---

config/agent.go

When `apm_enabled` is set to a falsy value the agent should pick it up
and exit.

config: allow disabling agent

---

model/normalizer.go
model/normalizer_test.go

Also discard the message about annotations because they have not been
implemented (yet).

[normalizer] only accept strictly positive durations

---

README.md

Add simple steps on how to run the Agent on OSX.
I also provided a build in the releases for our last version 5.2.3.

Add documentation on how to run on OSX

---

watchdog/info_test.go

On fresh OSX Sierra installs, number of max open file descriptors is set to 256. Thus, the TestNetHigh test with 1000 servers is too much.
I'm not a big fan of this change, but the only other option I see is to ask the developer to change his system settings.

tests watchdog: only run TestNetHigh with 200 servers

---

agent/receiver.go

follows up on the discussion in #266 to actually stop binding to the legacy port 7777

drop legacy receiver port

---

model/decoder.go
model/span_gen.go

In JRuby interpreter, unsigned int are sent as ``int`` type (Java related type system). This patch will handle IDs so that they're cast from ``int`` to ``uint``.

[decoder] graceful accept uint64 values if they're sent as int64 for ids

---

agent/agent.go
model/span.go
model/stats.go
model/stats_test.go
model/statsraw.go
model/top_level.go
model/top_level_test.go

This adds:
- a `TopLevel` func on spans which returns a boolean telling wether it's top-level or not
- a `TopLevel`member to stats, which contains the number of top-level spans contributing to it

[toplevelname] identifying top-level name spans

---

model/stats.go
model/stats_test.go
model/statsraw.go

Similar to https://github.com/DataDog/datadog-trace-agent/pull/281 to some extent. Switching from int64 to float64 is fine (new code reading float64 will also accept int64 as it transits in JSON).

[toplevelname] added sampling support to top-level count

---

agent/agent.go
agent/concentrator.go
agent/concentrator_test.go
agent/model_test.go
fixtures/stats.go
model/span.go
model/stats_test.go
model/statsraw.go
model/top_level.go
model/top_level_test.go
model/trace.go

I basically followed the pattern used when we met the same problem with the weight: compute the value beforehand and cache it in some external data struct. Main pros are:
- avoids locking the span fields
- avoids touching the span structure, as everything is out-of-band, not in the main data model
Cons:
- more parameters to functions, which already carry the span + the weight + the list of top_level spans within the trace + the sublayers + ...

[toplevelname] fix concurrent map access

---

fixtures/span.go
model/span.go
model/span_test.go

Two things here:
- allowing a call to `Weight` on a nil span (stumbled on that case during a test of some internal tool, it's not a mainstream case, but I prefer to anticipate it)
- some fixtures fixes (same thing, used by internal tool, which can not tweak the `weight` and `topLevel` fields as those are private)

[toplevelname] minor fixes concerning top-level name support

---

config/agent.go
config/config.go
config/config_test.go

`ExtraAggregators` allow certain span metadata fields to be
elevated to top-level keys in `StatsBucket`s. The downstream
effect is to generate metrics with this additional dimension in Datadog's backend
A default `http.status_code` aggregator will inspect incoming spans for the eponymous
metadata, and create the following metrics downstream:
- `trace.<name>.errors.by_http_status`
- `trace.<name>.hits.by_http_status`
both tagged by `http.status_code` (e.g. `500`) and `http.status_class` (e.g. `5xx`)

config: add the http.status_code aggregator by default

---

Rakefile
gorake.rb

These are really small changes to make the Windows build work better.
The date command on Windows does not behave like the unix one so I switched to a ruby function, this changes slightly the format:
before: 2017-06-14T12:35:34-0400
after: 2017-06-14T12:35:34-07:00
And I changed the way environment variables are set in rake for windows since it broke in the windows cmd shell.

Fix minor bugs in Windows build

---

quantizer/sql_test.go
quantizer/tokenizer.go

The quantizer would return "Non-parsable SQL query" whenever those patterns would be found:
```
`letter-letter` `letter.letter` "letter.letter" "letter-letter"
```
This bug was found by a client with the following sql query that won't be parsed : 
```
INSERT INTO `table-21`.issues
```

Fix quantizer edge case

---

agent/concentrator.go
model/stats.go
model/stats_test.go
model/statsraw.go

StatsBucket bucket already holds the duration distribution, but there's not other dimension to that information. Thus, when we have 50 spans in the 20ms duration slice, we don't know how many were errors.
This PR adds the ErrDistributions map to StatsBuckeet, and only spans makred as errors are considered when adding to it.
Commit  bec6280 updates stats.go and statsraw.go to add the mapping and consider the span if it's an error, as well as stats_test.go to if spans marked as errors are counted correctly.

Add Error Duration Distribution to Stats

---

agent/agent.go
agent/endpoint.go
agent/endpoint_test.go
agent/receiver.go
agent/receiver_test.go
agent/writer_test.go
model/payload.go

Since the Receiver now collects data about incoming languages, compose an HTTP header that contains this info for reporting to the backend. 
Header value is a pipe-separated alphabetical string of languages, like so:
```
X-Datadog-Reported-Languages: go|java|python
```

propagate language data in payload headers

---

quantizer/sql.go
quantizer/sql_test.go

The `GroupFilter` doesn't take in account question marks that are not separated by commas. In that case, the result is a wrong query quantization:
```
--- FAIL: TestSQLQuantizer (0.00s)
Error Trace:    sql_test.go:263
Error:		Not equal: "insert into user ( id, email, name ) values ( ? )" (expected)
!= "insert into user ( id, email, name ) values ( ? ?, ? )" (actual)
```
This PR ensures that `( ? ?, ? )` is `( ? )`.

[lexer] group question mark even without a comma

---

Rakefile

(which is used by the windows agent build script)
Made this change because the :windows target appears to be intended for cross-compilation.  Made change for the :build target for native Windows builds, which allows for (among other things) the agent6 build to build (and include) the APM agent.

[Windows]  Add windows specific executable name for the :build target

---

agent/endpoint.go

Add timeout between the agent and the backend

---

agent/stats.go

If a restarted trace-agent doesn't receive traces within the first stats
reporting window (10 seconds) it can deadlock in the [receiver stats loop](https://github.com/DataDog/datadog-trace-agent/blob/e3d35255d748cdb9aa5d4f8c30763b8aa752fbb3/agent/receiver.go#L277-L298).
The direct symptom of this is that stats under `datadog.trace_agent.receiver.*`
and `datadog.trace_agent.heartbeat` fail to report
This ensures we always release the read lock even in the absence of Stats.
Example stack dump of a blocked goroutine:
```
goroutine 44 [semacquire, 21 minutes]:
sync.runtime_Semacquire(0xc420191808)
/usr/local/go18/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).Lock(0xc420191800)
/usr/local/go18/go/src/sync/rwmutex.go:91 +0x6e
main.(*receiverStats).reset(0xc420191800) …
```

trace: fix deadlock when no stats present

---

Rakefile

The command to build the windows target was broken because of mistake when concatenating the two parts of the command.

Fix bug in Windows rake command

---

agent/agent.go
agent/receiver.go
agent/stats.go

- use a different metric tag to count traces manually prioritized
- fix multiline logging
- expire receiverStats tagset
Example of previous output: multi-line, one tag set.
```
2017-10-12 12:19:39 INFO (receiver.go:316) -
[lang:go lang_version:1.9.1 interpreter:gc-amd64-linux tracer_version:v0.5.0] -> traces received: 21358, traces dropped: 0, traces filtered: 0, traces amount: 14167935 bytes, services received: 0, services amount: 0 bytes
[] -> traces received: 0, traces dropped: 0, traces filtered: 0, traces amount: 0 bytes, services received: 0, services amount: 0 bytes
```
After this PR, is should simply look like:
```
2017-10-12 12:19:39 INFO (receiver.go:316) - [lang:go lang_version:1.9.1 interpreter:gc-amd64-linux tracer_version:v0.5.0] -> traces received: 21358, traces dropped: 0, …
```

Misc improvements

---

agent/agent.go
agent/receiver.go
agent/stats.go

- log the actual content of the stats `Strings`, not its indexes 
- proper `strings` init, to avoid having empty strings from initialization.
- hide the empty `""` tagStats.

Fix tagStats logging

---

agent/agent.go
agent/agent_test.go
model/normalizer.go
model/normalizer_test.go
model/truncator.go
model/truncator_test.go

This is to ensure that strings (ex. query strings) stored in certain fields, such as `resources` are still parseable and are quantized properly. 
Tested in staging and prod

[trace] Moving quantization before truncation of spans

---

agent/agent.go
agent/agent_test.go
agent/main.go
agent/main_nix.go
agent/main_windows.go

This PR extracts the logic of providing an exit channel out of the `runAgent` function, that way we can have different exit conditions:
- SIGINT or SIGTERM on unix
- service STOP or SHUTDOWN when it is running as a windows service

Graceful shutdown for Windows Service

---

agent/log.go
config/agent.go
config/agent_nix.go
config/agent_windows.go

The previous default log path assumed that the agent was running on a Unix system. This PR fixes that.

Change default log path on Windows

---

agent/info.go

Similar to https://github.com/DataDog/datadog-trace-agent/pull/328 but for the info page.
Currently we report things like: 
```
--- Receiver stats (1 min) ---
-> tags: go, 1.9.1, gc-amd64-linux, v0.5.0
Traces received: 30425 (19674323 bytes)
Spans received: 60850
Services received: 0 (0 bytes)
Total data received: 19674323 bytes
------------------------------
--- Receiver stats (1 min) ---
-> tags: None
Traces received: 0 (0 bytes)
Spans received: 0
Services received: 0 (0 bytes)
Total data received: 0 bytes
------------------------------
```
This PR removes the latter section.

Remove empty tag set from info page

---

agent/main.go
agent/main_nix.go
agent/main_windows.go
glide.lock
glide.yaml

This will help with system-level orchestration.
depends on: `github.com/DataDog/datadog-agent/pkg/pidfile`

[pidfile] add pidfile if so specified

---

agent/agent.go
agent/main.go
agent/receiver.go
agent/receiver_test.go
agent/sampler.go
gorake.rb
info/endpoint.go
info/info.go
info/info_test.go
info/sampler.go
info/stats.go
info/version.go
writer/endpoint.go
writer/endpoint_test.go
writer/writer.go
writer/writer_test.go

Extract `info` and `writer` packages to reduce the size of the `main`, simplify future development, help separate concerns.
As future work is going to add various elements to the writer, I initially extracted the `writer` (with the `endpoint.go`) into another package. But for it to work I needed to extract `info` too.
The PR introduces no logic change. It is just about moving struct/functions/variables to other packages, and making public the ones that have to.

Extract info and writer packages from main

---

Rakefile
agent/agent.go
agent/agent_test.go
agent/concentrator_test.go
filters/resource_test.go
fixtures/span.go
fixtures/trace.go
model/client_api_test.go
model/compat.go
model/normalizer_test.go
model/span.go
model/stats_test.go
model/sublayers.go
model/sublayers_test.go
model/top_level_test.go
model/trace.go
model/trace_gen.go
model/trace_test.go
model/weighted_span.go
quantizer/cassandra_test.go
quantizer/main.go
quantizer/redis.go
quantizer/redis_test.go
quantizer/sql.go
quantizer/sql_test.go
sampler/prioritysampler_test.go
sampler/scoresampler_test.go
sampler/signature.go
sampler/signature_test.go

Another step before the global introduction of protobuf.
By using references it will simplify the code migration (as generated protobuf structs also include themselves by reference).
That should also avoid various struct copies.
Notes:
- for `model/trace_gen.go`, I simply ran `msgp -file=model/trace.go -marshal=false`. That should be enough as `trace_gen.go` isn't a file we manually modified. I also checked to simply regenerate the file without the `Trace` change and I got exactly the same file as before so the generation method is good. 
- `Quantize` is now in-place.
- The PR is based on the protobuf PR ; I'll merge them together once I've tested them enough.

Replace Trace []Span with []*Span

---

Rakefile
info/info.go
info/info_test.go
info/sampler.go
info/stats.go
info/version.go

Lint `info` and `writer` packages, which were missing as the Rakefile wasn't processing them since the last code reorganization.

Add missing packages from linting/testing

---

agent/receiver.go
agent/receiver_test.go
fixtures/trace.go

This PR targets a bug we've observed where sometimes the agent will send a HTTP 200 response before all the request's body has been received, which leads to the connection being reset and dropping traces.

Always drain requests before responding

---

backoff/backoff.go
backoff/backoff_test.go
backoff/exponential.go
backoff/exponential_test.go
backoff/fixtures.go
fixtures/random.go
fixtures/trace.go
info/writer.go
statsd/fixtures.go
statsd/statsd.go
writer/datadog_endpoint.go
writer/endpoint.go
writer/fixtures.go
writer/payload.go
writer/payload_test.go
writer/service_writer.go
writer/service_writer_test.go
writer/stats_writer.go
writer/stats_writer_test.go
writer/trace_writer.go
writer/trace_writer_test.go
writer/writer.go

Includes:
* More modular structure for extra code reuse and cleaner testing.
* Readdition of retriable errors.
* Async flushing of payloads handled by a PayloadSender.
* Addition of exponential jittery backoff timer used by default by the new PayloadSender.
Working on top of: https://github.com/DataDog/datadog-trace-agent/pull/343

Async flushing of writer payloads with jittery exponential retrying

---

agent/trace-agent.ini
backoff/exponential.go
backoff/exponential_test.go
config/agent.go
config/config.go
writer/config/payload.go
writer/config/service_writer.go
writer/config/stats_writer.go
writer/config/trace_writer.go
writer/payload.go
writer/payload_test.go
writer/service_writer.go
writer/service_writer_test.go
writer/stats_writer.go
writer/stats_writer_test.go
writer/trace_writer.go
writer/trace_writer_test.go
writer/writer.go

This PR exposes most of the configurations surrounding the new senders and queues for trace, stats and service writers.
This way, these details can be tuned without need for a recompilation.

Allow configuration of trace, stats and service writers.

---

agent/agent.go
agent/service_mapper.go
agent/service_mapper_test.go
agent/trace_service_extractor.go
agent/trace_service_extractor_test.go
model/services.go
model/services_test.go
writer/service_writer.go
writer/service_writer_test.go

This PR adds `TraceServiceExtractor` to our trace processing pipeline. The idea is extract service metadata out of all top-level spans belonging to a given trace and send them downstream (to `ServiceWriter`).
By doing this we intend to simplify instrumentation on the client side, since we no longer require service metadata to be set at the tracer level.
Based on feedback from @LotharSee and @ufoot I've made the following changes:
* Created `ServiceMapper` which should be now the entry point for ingesting `ServicesMetadata` (either coming from HTTP requests or from metadata embedded on traces). `ServiceMapper` is just a cache layer around `ServiceWriter`;
* Removed caching functionality/`DeepEqual` logic from `ServiceWriter`;

Refactor service metadata pipeline

---

quantizer/sql_test.go
quantizer/tokenizer.go

Updates a contributor PR: #320 
It adds support for MySQL comments (inline especially) that are not properly removed from the Agent quantizer:
```
--- FAIL: TestSQLQuantizer (0.00s)
Location:       sql_test.go:307
Error:		Not equal: "select * from users where id = ?" (expected)
!= "select * from users where id = ? # This comment continues to the end of line" (actual)
```
This patch solves the problem.

quantizer: support MySQL comments

---

agent/trace-agent.ini
writer/service_writer.go
writer/service_writer_test.go

Since we only send increments as opposed to full snapshots of service metadata, we must support enqueuing multiple payloads for `ServiceWriter`.
Should we also raise the default `MaxAge` configuration param for queued payloads? A single-service payload is less than 100 bytes, and the service number tends to be small as well (in the order of dozens), so I think it should be safe to increase it.

Let multiple payloads to be enqueued on `ServiceWriter`

---

agent/trace-agent.ini
model/normalizer.go
writer/config/payload.go
writer/payload.go
writer/trace_writer.go

- Reduce `queue_max_bytes` down to 64MB. It is a safer default for customers, up to approximatively 200-250% the normal memory usage.
- Reduce log verbosity in debug mode.

Reduce debug log verbosity and reduce max sender memory usage

---

agent/agent.go

Both signature and priority sampler can access the `span.Metrics` map (to access either `samplingPriorityKey` or `SpanSampleRateMetricKey`) at the same time when dealing with traces with a priority. It can result in a race condition.
```
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) | fatal error: concurrent map read and map write
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) |
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) | goroutine 3024 [running]:
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) | runtime.throw(0x9fea58, 0x21)
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) |        /home/jenkins/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x95 fp=0xc4204cada0 sp=0xc4204cad80
2018-02-15 12:52:34 UTC | ERROR | (apm.go:95 in func2) …
```

Fix race condition on dual sampling

---

config/README.md
config/merge_env.go

Add support for the `DD_APM_NON_LOCAL_TRAFFIC` env variable.
`bind_host` will disappear with Datadog Agent 6 in favor of apm_non_local_traffic.
This new variable will be useful to the docker environment.

Add DD_APM_NON_LOCAL_TRAFFIC env var

---

.gitignore
gorake.rb

build: update windows build paths

---

sampler/backend.go
sampler/coresampler.go
sampler/memory_backend.go
sampler/memory_backend_test.go
sampler/presampler.go
sampler/presampler_test.go
sampler/prioritysampler_test.go
sampler/score.go
sampler/scoresampler_test.go

Make `Backend` an interface.
It should make the code more explicit about what it exposes, and will allow a better reusability/flexibility.

Make Backend a MemoryBackend of a Backend interface

---

.circleci/config.yml
cmd/trace-agent/service_mapper.go
cmd/trace-agent/service_mapper_test.go
gorake.rb
statsd/fixtures.go
writer/fixtures.go
writer/payload_test.go
writer/service_writer_test.go
writer/stats_writer_test.go
writer/trace_writer_test.go

Running the tests with `go test -race /....` reveals several race conditions. This PR fixes them and enables the flag. It slows CI down a bit but adds more thread-safety.

 {cmd,statsd,writer}: fix race conditions in tests

---

Makefile

The build was failing on windows because the cleanup command is invalid. It's not needed anyway.

Makefile: do not use rm on windows

---

README.md

Instructions weren't up to date now that the trace-agent is shipped with the Datadog Agent on Windows.

Update README with proper windows instructions

---

fixtures/statsd.go
writer/fixtures.go
writer/payload_test.go
writer/service_writer_test.go
writer/stats_writer_test.go
writer/trace_writer_test.go

- Moves `statsd/fixtures.go` to `fixtures/statsd.go`
- Makes test functions and types meant for testing unexported in `writer/fixtures.go`

{statsd,writer}: keep fixtures private and limited to tests

---

cmd/trace-agent/agent.go
cmd/trace-agent/concentrator.go
cmd/trace-agent/concentrator_test.go
model/sublayers.go
model/trace.go
model/trace_test.go

Until now sublayers were only computed for the root span of each trace. We now compute it for all non leaf top level spans of the trace. The purpose being to fix some gaps in the data currently shown in the UI.
This is implemented by extracting all relevant subtraces in each trace and computing the sublayers for each of theses subtraces individually.
One consequence of this change is that now the complexity of computing sublayers is no longer `O(s)` with `s` the number of spans, but `O(s * t)` with `s` the number of spans and `t` the number of top level spans. Which may have a very significant performance impact on some pathological traces.
It has been deployed on staging and I haven't noticed any significant change on the CPU footprint from  trace-agent.

Compute sublayers for non root toplevel spans

---

quantizer/sql.go
quantizer/sql_test.go
quantizer/tokenizer.go

This change replaces SQL `LIMIT` values (and pairs of values) with `?`
to reduce resource cardinality.
Fixes #390

quantizer: reduce limited SQL query cardinality

---

Makefile
cmd/trace-agent/agent.go
cmd/trace-agent/agent_test.go
cmd/trace-agent/listener.go
cmd/trace-agent/main.go
cmd/trace-agent/main_nix.go
cmd/trace-agent/main_windows.go
cmd/trace-agent/receiver.go
cmd/trace-agent/receiver_test.go

In this change:
* Removes `exit` channel from StoppableListener and instead just uses [`(*http.Server).Shutdown`](https://golang.org/pkg/net/http/#Server.Shutdown) from the standard library (introduced in Go 1.8)
* Removes `exit` channel from the agent and instead uses the more idiomatic cancellation context.
* Adds the Windows build to CI.

cmd/trace-agent: remove exit channels in favor of http.Server and context.Context

---

config/agent.go
config/merge_ini.go
config/merge_yaml.go
writer/client.go

This should permit use-cases of running the agent behind a proxy such as `haproxy`, using the `skip_ssl_validation: true` setting in the config file.

writer: inherit and use "skip_ssl_validation" setting from Agent v{5,6}

---

writer/payload.go
writer/payload_test.go
writer/service_writer.go
writer/service_writer_test.go
writer/trace_writer.go

* Payload queue could become stuck if queued payloads all expired due to max age before next flush (queue would become of size 0, so we'd never leave the queue state but we'd also never schedule a new retry).
* Clean old (bigger than max age) payloads when inserting new ones not just on flush.
* When we can't serialize a trace or service payload, we should reset our buffers because otherwise we'll probably end up in a serialization error loop and no progress will be made.
* Fixed a flaky test in service writer after logic changes to the buffering mechanism.

Improvements to trace writer and payload queue behaviour.

---

cmd/trace-agent/agent.go
filters/base.go
filters/resource.go
filters/resource_test.go
filters/tag.go
filters/tag_test.go

Extends the `replace_tags` rules to apply to all spans, not only the root.

Apply tag replacement to all spans instead of root only

---

quantile/weighted.go

`rand.Seed(7337)` was called on every call to `probabilisticRound` which was both incorrect and  very slow since it was equivalent to having a single hard coded float to do all the roundings and calls to `rand.Seed` are very expensive.

Fix performance issue in quantile.WeighSummary

---

config/merge_env.go

config: support overriding agent endpoint via env

---

config/merge_yaml.go

Fixes https://github.com/DataDog/datadog-trace-agent/issues/399
This change allows configuring the log file location for the agent by setting the `log_file` value in the `apm_config` section of the YAML file.
e.g.:
```
apm_config:
log_file: /my/log/file.log
```

config: account for log_file coming from yaml

---

writer/service_writer.go
writer/stats_writer.go
writer/trace_writer.go

While letting the trace-agent run on an ARMv7 system (32bit), I encounter some segmentation faults with atomic operations. This is a familiar issue in go, please see https://golang.org/pkg/sync/atomic/#pkg-note-BUG
To fix this, I moved the structs containing the values to be written atomically to the top of the parent struct to ensure that they are 64bit aligned. See link above
> The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

writer: ensure 64bit alignment on 32bit systems

---

cmd/trace-agent/agent.go
cmd/trace-agent/sampler.go
info/info.go
info/sampler.go
sampler/coresampler.go
sampler/prioritysampler.go
sampler/scoresampler.go

This PR add a dedicated error sampler to the trace-agent. The goal of this is to keep more error traces (which are the most interesting ones).
With this PR the `trace-agent` will maintain two different score samplers that will each have their own maximum TPS. One for traces containing errors and one for other traces. That way the TPS of errors that the agent sends to the API will be independent from the TPS of traces containing no errors.

Add dedicated error sampling

---

quantizer/redis.go

Fixes a panic which occurred in situations where the number of arguments
was "unorthodox".

quantizer: make sure there are enough elements in slice before accessing

---

model/normalizer.go
model/normalizer_test.go

Fixes errors that were logged with an empty name, eg:
"dropping trace reason: invalid span  span.normalize: invalid `Name`:"

model: Use original metric name if parsing had an error.

---

info/info.go

This fixes a problem where the `info` command was failing due to a
non-standard `bind_host` setting. The `info` command was always
attempting to reach the /debug/vars endpoint on `localhost`. This would
of course not work when the `bind_host` value was different.
Fixes DataDog/dd-agent#3653

info: use bind_host when querying /debug/vars

---

cmd/trace-agent/agent.go
cmd/trace-agent/transaction_sampler.go
cmd/trace-agent/transaction_sampler_test.go
info/writer.go
writer/trace_writer.go
writer/trace_writer_test.go

This PR reworks the logic around trace and transaction writing to fix some identified issues.
Traces are no longer arbitrarily split when writing. This introduced some issues later on in the server side processing pipeline, specially around priority sampling.
Instead, `MaxSpansPerPayload` is now a soft-limit. Whenever possible, payloads will respect said limit. In case a single trace + its transactions have more spans than that limit, then we still attempt to send that trace (on its own) to Datadog's API. There's a chance that the API will reject it if it goes over the input size limit but, if that happens, that means the trace is several MB big which is not normal anyway so the issue should be handled at the client side.
Before, traces and transactions were written asynchronously which …

cmd/trace-agent: improvements to trace/transaction writing pipeline.

---

config/agent_test.go
config/merge_env.go
config/merge_env_test.go
config/merge_ini.go
config/merge_yaml.go

This PR makes it possible to configure spans to be analyzed as transactions with a environment variable. The format for this environment variable is:
```
DD_APM_ANALYZED_SPANS="service_name|operation_name=1,other_service|other_operation=0.5"
```

config: make analyzed_spans configurable with an environment variable

---

cmd/trace-agent/main.go

**main: add a metric when the agent starts.**
This metrics allows to track the restarts of the trace-agent,
independently from whatever supervisor it's using.

cmd/trace-agent: add a metric when the agent starts.

---

writer/datadog_endpoint.go

User-Agent: A helpful information to have. Instead of the Go default
(`Go-http-client/1.1`), the string will be unique to the tracer, will
have the version, and a link to this GitHub repo (example: `Datadog Trace Agent/6.2.0/422142 (+https://github.com/DataDog/datadog-trace-agent)`).

writer: Set additional HTTP headers when querying Datadog.

---

config/merge_ini.go
config/merge_yaml.go
info/writer.go
writer/config/stats_writer.go
writer/stats_writer.go
writer/stats_writer_test.go

Adds a splitting logic in the stats writer in order never to exceed a pre-configured maximum number of "entries" in a stats payload.
Doing so ensures we don't hit the maximum payload size of the Datadog trace intake API.
The first commit is just a cleanup of the stats writer code, and some added comments.
The second commit adds the configuration value `max_entries_per_payload`. This value should be tweaked very cautiously. Setting it too low will have the agent send much more payloads than it should when flushing, which will impact performances and will hit the backend significantly more. Setting the value too high, and the payloads might end up being rejected due to their size.
The third commit is the actual splitting logic + unit tests.

writer: split stats writer payloads based on number of entries.

---

.circleci/config.yml
Makefile
cmd/trace-agent/receiver.go
sampler/coresampler.go
sampler/scoresampler.go
writer/trace_writer_test.go

This makes `golint` use exit status 1 when linting errors are found. It
also fixes any already-existing linting errors.

build: make build fail on linting errors.

---

quantizer/sql.go
quantizer/sql_test.go
quantizer/tokenizer.go

This change alters the tokenizer to allow `:=` assignments in SELECT
parameters, treating them as regular assignments. Previously this would
cause the parser to return an error and fail to tokenize the query.
Now `:=` will be seen as a valid assignment.

quantizer: allow variable assignments in SQL queries

---

.gitignore
Makefile
README.md

Allows running:
```bash
make binaries V=6.2.1
```
Which would result in checking out and compiling the binaries for revision `6.2.1` into the `./bin` folder. They are named `trace-agent-{$GOOS}-{$GOARCH}-6.2.1`

Makefile: add 'binaries' command to help release pre-compiled binaries.

---

config/merge_yaml.go

This adds the `connection_limit` configuration option to the yaml
configuration `apm_config` section to match the `ini` settings.

config: add "connection_limit" option to yaml config

---

Makefile
flags/flags.go
flags/flags_nix.go

Packages `flags` and `osutil` were missing from linter.

Makefile: add new packages to linter

---

datadog.example.yaml

Adds an `example.yaml` configuration to serve as guidance for an overview of all agent configuration options.

doc: add example yaml file

---

config/agent.go
config/agent_nix.go
config/agent_windows.go

This change fixes a regression where the Python environment was removed
from the host acquiring process in #435 
The Python environment is needed because it uses a Datadog-specific
library which covers for scenarios such as GCE, EC2, Docker etc. for
hostname retrieval.

config: use Python environment as fallback to compute hostname

---

config/agent_test.go
config/merge_yaml.go
config/test_cases/full.yaml
obfuscate/http.go
obfuscate/http_test.go
obfuscate/obfusacte.go
obfuscate/sql.go

Enables opt-in obfuscation of `http.url` tags in `http` type spans and of `error.stack` tags in all span types.

obfuscate: added obfuscator for http.url and error.stack

---

.circleci/config.yml
obfuscate/json.go
obfuscate/redis.go

A small performance hit is observed:
```
name                  old time/op    new time/op    delta
ObfuscateJSON/5003-8    48.4µs ± 0%    46.9µs ± 0%   -3.10%
ObfuscateJSON/437-8     6.77µs ± 0%    6.64µs ± 0%   -1.93%
ObfuscateJSON/671-8     6.81µs ± 0%    6.86µs ± 0%   +0.73%
name                  old alloc/op   new alloc/op   delta
ObfuscateJSON/5003-8    22.1kB ± 0%    23.8kB ± 0%   +7.41%
ObfuscateJSON/437-8     2.95kB ± 0%    3.47kB ± 0%  +17.62%
ObfuscateJSON/671-8     3.02kB ± 0%    3.47kB ± 0%  +15.12%
name                  old allocs/op  new allocs/op  delta
ObfuscateJSON/5003-8       203 ± 0%       199 ± 0%   -1.97%
ObfuscateJSON/437-8       48.0 ± 0%      46.0 ± 0%   -4.17%
ObfuscateJSON/671-8       42.0 ± 0%      40.0 ± 0%   -4.76%
```

obfuscate: s/strings.Builder/bytes.Buffer (downgrade to go1.9.4)

---

obfuscate/http_test.go
obfuscate/obfuscate.go
obfuscate/obfuscate_test.go

Adds `web` as obfuscated `Span` type with `obfuscateHTTP`.

obfuscate: add `web` span type to obfuscated HTTP tags

---

cmd/trace-agent/agent.go
cmd/trace-agent/transaction_sampler.go
cmd/trace-agent/transaction_sampler_test.go
sampler/prioritysampler.go
sampler/prioritysampler_test.go

This PR makes sure that when a span from a trace with a sampling priority of 2 matches the criteria to be analyzed it is kept even if the rate based sampling policy would discard it.
Since these traces have been flagged as being of particular interest by the user, it makes sense to ensure the transactions too are always kept.

cmd/trace-agent: force sampling of transactions with priority 2

---

config/agent.go
config/merge_env.go
config/merge_yaml.go
datadog.example.yaml
writer/client.go
writer/client_test.go

This change adds support for the `DD_PROXY_HTTPS` and (now deprecated) `HTTPS_PROXY` environment variables in the trace agent. This is to match existing (and expected) Datadog Agent behavior.

config: added proxy environment variable support

---

config/agent.go

If the trace agent fails to acquire a hostname after trying all fallbacks, it should fail to start.

config: fail start-up when hostname is empty

---

.circleci/config.yml
README.md
config/merge_ini.go
obfuscate/json.go
obfuscate/redis.go
obfuscate/redis_tokenizer.go

This change updates JSON and Redis obfuscator to use `strings.Builder`
instead of `bytes.Buffer` for a minor speed increase. It also updates CI
to use go1.10, where this new structure was added.
Additionally, it also fixes a minor bug with an error message in the `config`
package.

obfuscate: use strings.Builder from go1.10

---

obfuscate/sql_test.go
obfuscate/sql_tokenizer.go

This change reverts a previous change where quoted strings were
incorrectly treated as identifiers by the tokenizer to avoid their
obfuscation. Now, they are still identified as ID (identifier) but are
scanned as strings.
This matches the behavior of the original `youtube/vitess` package
[here](https://github.com/youtube/vitess/blob/addf2c2907240612cb07a5fda2b47068b2e414c9/go/vt/sqlparser/token.go#L603).

obfuscate: treat strings as strings

---

obfuscate/obfuscate.go
obfuscate/sql.go
obfuscate/sql_test.go
obfuscate/sql_tokenizer.go

* **First commit**: resolves #475 
* **Second commit**: ensures that filters are reset every time a new obfuscator is initialized. Without this change, tests were failing when the filters returned tokenizing errors because the state was shared in a global object.

obfuscate: account for bracketed identifiers as AS parameters

---

Makefile
api/api.go
api/api_test.go
api/listener.go
api/logger.go
api/responses.go
cmd/trace-agent/agent.go
cmd/trace-agent/agent_test.go

The goal is to separate all the stuff from `cmd/trace-agent` into smaller packages and ultimately end up with a clear separation between the three main (high level) functionalities of the agent:
* API (aka receiver)
* Processing pipeline (sampling, collecting stats, etc. - currently cmd/trace-agent)
* Writers
Clearer separation will eventually facilitate better testing. There is no change to functionality.

cmd/trace-agent: factor out receiver into "api" package

---

config/merge_env.go
config/merge_yaml.go
config/merge_yaml_test.go
datadog.example.yaml

This change adds support for SOCKS5 proxies (which was practically already
supported via the existing proxy settings and their mechanics, but confusingly
implemented) using the `proxy.url` setting.
It also deprecates the unnecessary `proxy.http` and `proxy.https`
settings in the example files and marks them as such. The scheme can
already be deduced from the URL.

config: add support for SOCKS5 and deprecate proxy.http(s)

---

config/merge_env.go
config/merge_yaml.go
config/merge_yaml_test.go
datadog.example.yaml

This reverts commit b4b502c96691ad70e12fb90177180be22a83ff8d.
This change has to be postponed until it is part of the core agent. The
option added here does not exist in the core agent and has not yet been
decided as the key to use moving forward. Merging this will create
inconsistencies and complicated deprecation plans.

Revert "config: add support for SOCKS5 and deprecate proxy.http(s) (#478)"

---

obfuscate/obfuscate.go
obfuscate/sql.go
obfuscate/sql_test.go
obfuscate/sql_tokenizer.go

* Renaming and simplifying comments
* Removed `agent.parse.error` tag as it brought no real details about parsing errors.
* Reset obfuscator only once, before it runs.
No apparent impact on performance:
```
name                      old time/op    new time/op    delta
Tokenizer/Escaping/512-8    7.27µs ± 0%    7.30µs ± 0%  +0.32%
Tokenizer/Grouping/199-8    4.16µs ± 0%    4.17µs ± 0%  +0.19%
name                      old alloc/op   new alloc/op   delta
Tokenizer/Escaping/512-8    4.40kB ± 0%    4.40kB ± 0%   0.00%
Tokenizer/Grouping/199-8    2.72kB ± 0%    2.72kB ± 0%   0.00%
name                      old allocs/op  new allocs/op  delta
Tokenizer/Escaping/512-8      87.0 ± 0%      87.0 ± 0%   0.00%
Tokenizer/Grouping/199-8      68.0 ± 0%      68.0 ± 0%   0.00%
```

obfuscate: clean up SQL obfuscator

---

api/api.go
api/api_test.go
cmd/trace-agent/agent.go
config/agent.go
config/merge_ini.go
sampler/presampler.go
sampler/presampler_test.go

Remove unused `conf.PreSampleRate`, an option never meant to be exposed.
This is a no-op change. Only cleaning the code before future work on the pre-sampler.

config: remove configurable initial pre sample rate

---

config/agent_test.go
config/merge_env.go
config/merge_yaml.go
config/testdata/site_default.yaml
config/testdata/site_eu.yaml
config/testdata/site_override.yaml
config/testdata/site_url.yaml
datadog.example.yaml

Adds support for a new `site` top level configuration option, such that:
* When `site` is set, `https://trace.agent.<site>` is used.
* When both `site` and `apm_dd_url` are set, the latter takes precedence and user is notified.
* When only `apm_dd_url` is set, that value will be used.

config: add 'site' option

---

Makefile

Before such a fix, running `make ci` was failing on:
```
go get -u github.com/golang/lint/golint/...
package github.com/golang/lint/golint: code in directory /Users/benjamin/datadog/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```
After that change, the command works.

Fix make ci installation of golint

---

cmd/trace-agent/agent.go
cmd/trace-agent/transaction_sampler_test.go
model/span.go
model/top_level.go
model/top_level_test.go
sampler/coresampler.go

- Reorder the content of `Agent.Process` by more meaningful units and add extra comments.
- Add a `Span.SetMetric` function and use it in relevant places.
This prepare future changes involving that function and the usage of many more metrics.
It should have been two PRs (they are 2 commits) but as they are built on top of each other, I went for the easy way.

cmd/trace-agent: improve Agent.Process readability and add Span.SetMetric

---

cmd/trace-agent/agent.go
cmd/trace-agent/agent_test.go
cmd/trace-agent/concentrator.go
cmd/trace-agent/concentrator_test.go

This PR changes the way we aggregate and flush stats in the concentrator.
What it does.
- We no longer drop traces in `agent.Process`. The `concentrator` takes care of handling traces of any time itself.
- The previous constant of "2 active time buckets" is moved to `bufferLen`. You can see it previously used in `if model.Now()-2*a.conf.BucketInterval.Nanoseconds()` and `if ts > now-2*c.bsize` [1]. It still defaults to 2.
- `bufferLen` drives two things: it is the number of active time buckets for which we ingest statistics and the age of the time buckets we flush (aka. the delay before flushing a bucket).
- During a flush, we move from `bufferLen +1` active buckets (2 in the past + the current one) to `bufferLen` (the current one + the old one). That's the same behavior as before.
- …

Ingest old traces and align their stats on oldestTs

---

cmd/trace-agent/sampler.go
writer/fixtures_test.go
writer/payload.go
writer/service_writer.go
writer/stats_writer.go
writer/trace_writer.go
writer/writer.go

Fixes some (non-fatal) race conditions detected by the `-race` flag.

{cmd/trace-agent,writer}: fix race conditions

---

config/agent.go
writer/writer.go

Remove unused duplication of enabled field.

config: remove duplicated APIEnabled field

---

writer/datadog_endpoint.go
writer/datadog_endpoint_test.go
writer/endpoint.go
writer/fixtures_test.go
writer/multi_writer.go
writer/multi_writer_test.go
writer/payload.go
writer/payload_test.go
writer/service_writer.go
writer/service_writer_test.go
writer/stats_writer.go
writer/stats_writer_test.go
writer/trace_writer.go
writer/trace_writer_test.go

* Makes internal `writer` identifiers private
* Absorbs `BasePayloadSender` into `QueuablePayloadSender`
* Renames `QueuablePayloadSender` to `queuableSender`.

writer: make internal identifiers private

---

Gopkg.lock

Looks like latest versions of `dep` added some extra properties that make latest `dep check` runs fail.

dep: fix check warnings on dep 0.5.0

---

obfuscate/sql_test.go
obfuscate/sql_tokenizer.go

obfuscate: add exception when parsing empty-string identifiers

---

watchdog/info_test.go

This change removes the 1GB memory test in order to allow our tests to
run in the "medium" resource_class of CircleCI.

watchdog: remove high-memory consumption test

---

config/merge_env.go
config/merge_env_test.go

I'm opening this pull request because the same motivation as https://github.com/DataDog/docker-dd-agent/pull/291 . 
We are heavy users of APM and require a higher max_traces_per_second than what the default provides (10).
I know we can specify the value in datadog.yaml (tracer.sampler > max_traces_per_second), but it would be great if we can use an environment variable for it. Especially under container environment like Kubernetes, it's really useful and convenient.

config: enable to set "MaxTPS" from environment variable

---

cmd/trace-agent/concentrator.go

Attemtp to reduce UDP hits and flooding.
We had reports of excessive UDP packets (>3000 per 10 seconds) for metric `datadog.trace_agent.err_distribution.len`, all with values of zero. Seems uncalled for. This change should hopefully alleviate.

cmd/trace-agent: reduce histogram calls in concentrator

---

event/sampler_max_eps.go

This PR adds periodic max eps sampling reporting. This reporting is 2-fold:
* Statsd gauges for current, max, sample_rate and max_reached.
* Log lines prompting the user to tune the `MaxEPS` setting if the maximum event rate was reached.
Sample output:
```
=== RUN   TestEventProcessorFromConf/metric_-_above_max_eps
1541500869865907000 [Warn] Max events per second reached (current=193.66/s, max=100.00/s). Some events are now being dropped (sample rate=0.52). Consider increasing MaxEPS setting.
1541500899864986000 [Warn] Max events per second reached (current=224.48/s, max=100.00/s). Some events are now being dropped (sample rate=0.45). Consider increasing MaxEPS setting.
```

event: add max eps reporting.

---

event/processor.go
event/processor_test.go

Trace priority is stored as a metric on the root span.
Therefore, events extracted from the root span (the usual case) already include it by default. However, if events are extracted from non-root spans, they would not include the priority metric when sent to the backend so the backend would not know what priority they were associated with.
This PR ensures priorities are set on extracted event spans if the trace from which they were extracted contained a priority.

event: Ensure event priorities are propagated to Datadog backend.

---

config/config_windows.go
flags/flags_windows.go

and programdata
In the process of converting the entire (windows) agent from hard-coding to proper handling.
Dependent upon https://github.com/DataDog/datadog-agent/pull/2546

{config,flags}: change Windows paths from hard-coded to detecting program files

---

cmd/trace-agent/main_windows.go

build broken due to https://github.com/DataDog/datadog-trace-agent/pull/536.
Fixes build

Fix windows build

---

internal/config/env.go

This is so that when an environment variable is empty, it will be
ignored when being considered for overriding actual config values.

internal/config: use Getenv as opposed to Lookupenv

---

Makefile
README.md

Since the dependency update on datadog-agent in https://github.com/DataDog/datadog-trace-agent/pull/512 resulted in `cgo` becoming part of the build, it is no longer possible to cross-compile the binaries. This change updates the cross-compilation script to make use of [xgo](https://github.com/karalabe/xgo) to help with that.

Makefile: update cross-compilation script

---

internal/config/env.go

This fixes https://github.com/DataDog/datadog-trace-agent/issues/502

internal/config: allow setting environment using environment variable

---

internal/agent/normalizer.go

Slightly improves error messages, making them more consistent and in some cases more explicit.

internal/agent: slightly improve Normalize output

---

internal/config/env.go
internal/config/env_test.go

Adds new environment variables (correctly prefixed), marking others as deprecated:
* DD_APM_CONNECTION_LIMIT
* DD_APM_RECEIVER_PORT
* DD_APM_MAX_EPS
* DD_APM_MAX_TPS
* DD_APM_IGNORE_RESOURCES

internal/config: add DD_APM_ prefixed env. vars duplicates
