agent/model_test.go, model/stats.go, model/stats_test.go
Slightly faster assembleGrain implementation, less generic, hardcodes env, resource, service
=> [profiling] minor speed-up on assembleGrain

Rakefile, agent/dump.go, agent/main.go, agent/receiver.go, fixtures/services.go, profile/dumpservices.go, profile/dumpservices_test.go, profile/dumptraces.go, profile/dumptraces_test.go
Added `-dumptraces` and `-dumpservices` to dump all incoming input.
=> [profile] dump traces and services input

agent/receiver_logger.go
This would output negative values.
=> [receiver-logger] dumb mistake in skip error count

agent/listener.go
was found with go build -race on a prod node
=> [listener/race] fix conn lease data race bug

agent/receiver.go
The current constants are integer, and it does not map well to version
number. Moreover, they are initialized with iota, so version 0.1 is 0,
version 0.2 is 1, etc. Not very intuitive.
We now use explicit strings.
=> use strings for api version constants

agent/sampler.go
Reporting via expvar should be done with gauges when possible.
=> [sampler] fix expvar stats

README.md
https://github.com/DataDog/datadog-trace-agent/blob/benjamin/osx-doc2/README.md
=> Point OSX install procedure directly to latest binary

.gitignore, Rakefile, watchdog/info.go, watchdog/net.go, watchdog/net_windows.go
Proposal on how to build agent. This breaks, obviously, as some deps are not available for windows (the connection watchdog related tools AFAIK) but at least it should provide a command-line tool that does build a real windows exe.
=> [build] experimental windows build

CONTRIBUTING.md
=> [docs] update CONTRIBUTING with the right Slack channel

README.md
Added instructions to run the agent on Windows and some precisions relative to https://github.com/DataDog/dd-agent/issues/3382
=> Added Windows instruction in readme

model/normalizer.go, model/normalizer_test.go
=> Add protection against invalid status codes

agent/log.go
It's all in the comments, I was trapped seeing an agent dying with no log message at all, and it took me quite a time to find out what the error was.
=> [logger] flush raw loggers when throttled logger is flushed

agent/endpoint.go, agent/writer.go
Report all the metrics related to the endpoint + the number of services that are updated (which is import to detect some bugs related to the clients).
=> Add endpoint metrics

quantizer/sql.go, quantizer/sql_test.go
Add more context in the case we have an issue obfuscating an sql span resource.
=> Fix small bug

config/README.md, filters/resource_test.go
Also adds regression tests for resource filtering
=> Fix documentation example on filtering

agent/main_windows.go
Run the agent in the main goroutine and the control loop in another one to make sure we handle exit properly.
=> Run the agent in the main goroutine on Windows

agent/main_windows.go
Add stop notification when runAgent() returns
=> Add stop-pending notification immediately when stop is received.

writer/trace_writer.go, writer/trace_writer_test.go
Attempt to compress trace payloads with gzip before sending them to the trace api.
If compressing fails, revert to sending as identity.
=> Send traces compressed with gzip.

agent/agent.go, agent/sampler.go
Before, when using multiple samplers, the same trace could end up being
sent twice.
With this new logic. All involved samplers will be asked if the trace should be kept or not but the samplers themselves won't add it to the output. The agent will look at the decision of all samplers and if at least one said to keep the trace then the trace is added once to the output channel.
Also, signature sampler should be asked for ALL traces so that it has a non-biased vision of the distributions.
=> Refactor sampling logic to remove dupe sampled traces.

config/agent.go, config/agent_nix.go, config/agent_test.go, config/agent_windows.go, config/merge_yaml.go
If we're on agent6 let's try to grab the hostname using the agent's facilities.
Note: I'd like to improve the tests, but mocking Exec is a bit of a pain, so I'll do that in a separate PR.
=> [hostname] collect directly from agent6 if possible

Gopkg.lock, Gopkg.toml
Fixes some problems caused by converting from `glide` to `dep`.
=> build: fix dependency problems

cmd/trace-agent/agent.go
This PR makes sure we never send traces with negative priority to the backend.
=> Fix sampling of negative priority traces

README.md
=> README: clarify install instructions.

model/normalizer.go, model/normalizer_test.go
An attempt at enforcing valid utf8 strings for span contents after normalization.
It works but has a non-negligible impact which I couldn't avoid by writing the same code with several variations (my own loop, etc...). Most of the time and allocations are actually inside the Rune handling code of the stdlib it seems.
Impact on my MBP:
Impact with no invalid utf-8 strings:
```
$ benchstat old.txt new-valid.txt
name             old time/op    new time/op    delta
Normalization-4     549ns ± 8%     671ns ± 0%  +22.13%  (p=0.016 n=5+4)
name             old alloc/op   new alloc/op   delta
Normalization-4      792B ± 0%      792B ± 0%     ~     (all equal)
name             old allocs/op  new allocs/op  delta
Normalization-4      9.00 ± 0%      9.00 ± 0%     ~     (all equal)
```
Impact with …
=> model/normalizer: Enforce valid utf-8 during normalization.

model/normalizer.go
Previously it was possible to have errors of the form:
```
dropping trace reason: invalid span service:"demo" name:"say_hello" traceID:15524911522457890473 spanID:15524911522457890473 start:1527862614328407040..
```
Serving not much relevant information due to truncation. This change removes outputting the entire faulty span and slightly improves the specificity of the output.
=> model: improve normalization error logging

LICENSE-3rdparty.csv
For compliancy, we list licenses for used libraries (`core` and `testing` dependencies).
=> LICENSE: add 3rd party LICENSE

config/agent_test.go, config/merge_yaml.go, config/test_cases/full.yaml, obfuscate/memcached.go, obfuscate/memcached_test.go, obfuscate/obfuscate.go, obfuscate/obfuscate_test.go
Based on https://github.com/DataDog/datadog-trace-agent/pull/457
=> obfuscate: add memcached obfuscator

cmd/trace-agent/concentrator.go, model/stats_test.go, model/statsraw.go
This PR just simplifies part of the agent code by passing a slice value instead of a pointer.
=> Favor passing small value copy over pointer

cmd/trace-agent/main.go
=> cmd/trace-agent: cover for log level "warning"
